/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Conversations: typeof import('./components/Conversations.vue')['default']
    Conversatons: typeof import("./components/Conversatons.vue")["default"]
    Dark: typeof import('./components/Dark.vue')['default']
    Jarvis: typeof import('./components/Jarvis.vue')['default']
    MdMessage: typeof import('./components/MdMessage.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    PubSub: typeof import('./components/PubSub.vue')['default']
    README: typeof import("./components/README.md")["default"]
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TheCounter: typeof import("./components/TheCounter.vue")["default"]
    TheFooter: typeof import("./components/TheFooter.vue")["default"]
    TheInput: typeof import("./components/TheInput.vue")["default"]
    Upload: typeof import('./components/Upload.vue')['default']
    WebSocket: typeof import('./components/WebSocket.vue')['default']
  }
}
